### ISSUE TITLE
Auto-Compounding Frequency (Reinvesting Yields)

### ISSUE THREAD

**Issue by umphams** [umphams/yearn_mellow-gearbox-strategy#2]
Are we interested in `tend()` for this strategy, whether it be through the Yearn strategy or the underlying Mellow strategy?

### Context
**Style of accounting of all LPTs involved with the Mellow Strategy affects rewards timing**
   - if Mellow does not reward earlier LPs for the Mellow strategy per `period`, similar to `masterChef` style contracts, this effects how Yearn will time its investments into the strategy possibly.
   - This is only if Yearn wants to be strategic with its liquid assets in other strategies, and can wait and see what the APY is on a specific `period` within this strategy and wait til the last moment to invest in the already of credit account. ** tbh this seems like something that should not be allowed in the Mellow Strategy**

There are a number of different paths to take and I hope for discussion here to outline any incorrect assumptions, misunderstandings, and progress with a solid design path for this strategy. 

---
### Detailed Context

This is just me thinking out some of the research I have done regarding Mellow's strategy && the Yearn UX:

**Details:**

1. Every period, yearn bots would get `harvestTrigger()` to return `true` if:
    1. period is about to be done, or
    5. stopLoss hit, or
    6. rewardsClaim >> gasRequired (so taking profits makes sense && possibly reinvesting them depending on Vault’s debt allowance to strategy).

### Mellow Side:

So how does auto-compounding and rebalancing work for this strategy? *Context of how the Mellow Fearless Gearbox Strategy works:*

1. Yearn provides liquidity to Mellow Vault for Fearless wETH Gearbox Strategy
2. Mellow allocates liquidity in already open credit account, or new credit account depending on date respective to credit account periods (2 weeks typically)
5. Mellow has bots monitoring Margin Factors for the Gearbox strategies. It rebalances via adding to its credit account leverage position (lowering gearbox health factor), or removing (increasing gearbox health factor)
    1. Their take on Health Factor imo. Gearbox has health factors, that I think should still be monitored.
    2. Margin Factor, M > 1. So `M * x` is the equilibrium state that Mellow strives for in their Gearbox credit account. 
        1. ex.) If `M = 1.5`, then if `CreditAccountAssets_State = 1.25x`, then Mellow `adjustPosition()` to get more leverage in Gearbox credit account and integrate with curve/convex adaptors.
            1. This rebalances wrt to market prices for collateral vs leveraged tokens
               - Say if collateral token prices went up, but leveraged token prices did not, then there is more collateral and more debt to be taken out to reach equilibrium.

- [ ] **Question: Does it auto-compound claimed rewards in this sequence?**
    1. Couldn’t you make conditional statements to have this happen? NOTE: These are generic function names, not actual ones.
        
        ```solidity
        if(claim >= autoCompoundGasCost) { 
        
         claimRewards(); // claim 
         checkHealthFactor(); // some kind of helper function checking how hf is && if it can reinvest this yield
         adjustPosition(); // puts primaryToken into adaptor protocol within Gearbox (Curve/Convex in this case)
        
        }
        ```

**Comment by steve0xp** [comment]
This issue may be brought back as Mellow works on v2 codebase. Until then, it is handly mainly by monitoring bots from Mellow assessing the total health factor of the credit account during operations. Once the monitoring bot sees there is worthwhile opportunity to invest any earnings, then it does so. As for Yearn's sequencing on tending the yields to auto-compound, it will likely come about when spurring monitoring at the direct source (gearbox) which will come later.
