### ISSUE TITLE
Holistic strategy design wrt to harvestTrigger() conditions & functionality

### ISSUE THREAD

**Issue by umphams** [umphams/yearn_mellow-gearbox-strategy#4]
**☑️ Goal: figure out the holistic routing when thinking about the KEEP3R calls and manual calls from vault to strategy.**

Started out by thinking about considering having harvestTrigger() have conditional code checking that the `period` is close to elapsing.

> **NOTE - this is my simplistic understanding of the `harvest()` flow:**
> 
> via `harvestTrigger()` implementation code, check certain conditions to warrant a `harvest()` call from a yearn bot. `harvest()` then pulls at the least the rewards out of the strategy (`MellowVault`). It does that via `registerWithdraw()`. The timing would have to be figured out, but ultimately at the end of the `period,` the Yearn vault would get any requested funds.

### Moving onward:
**Consider having a bot not call `harvest()` w/ a nonzero `_debtOutstanding` unless the vault really needs to access illiquid strategy assets.**

This is because of the partial illiquidity due to `period` duration for underlying Gearbox credit account lifespan. Thus, `harvest()` would be called to just get accounting, claim rewards, BUT NOT liquidate. 

If someone manually calls `harvest()` w/ a nonzero value for `_debtOutstanding`, then `withdrawSome()` would not actually successfully change the balance of `want` token, all it would do is queue up a withdraw. 

- [ ] **TODO - have talks with Mellow to have them auto-push yearn the withdrawal amount, otherwise, we'll have to have a separate bot claim it or something.**

**Comment by steve0xp** [comment]
This is continued in a new issue #7 after having discussions with Val John.
