### ISSUE TITLE
Where does the strategy measure health metrics from: Yearn (internal calcs), Mellow, or Gearbox?

### ISSUE THREAD

**Issue by umphams** [umphams/yearn_mellow-gearbox-strategy#5]
Bot monitoring: **It is important to be aware of the health factor of the actual strategy, but are we trusting these metrics based on:**

1. Mellow metrics - their system where they use Marginal Factor Balance & State checks?
2. Gearbox metrics - health factors for specific credit accounts?
3. Yearn own metrics - health bots querying blockchain to see value of assets based off of converting assets in open strategy positions & other internal math

_Context:_
- Mellow uses M*x as the Marginal Factor Balance that is strives to have. Basically `M` is the marginal factor, `x` is the total USD for assets in a strategy. Rebalancing occurs to ensure that this is in a healthy state, defined by the strategist I think.
- Gearbox monitoring: view functions available to see total && twv && hf. Yearn could check the hf directly for the mellow-gearbox credit account and gauge if they want to withdraw or not based on this and any other internal aspects (perhaps Yearn has its own way of calculating the `hf` with it's own `twv` calculation. --> ex. I'm not sure how the max price drop during liquidation is calculated in gearbox.

```
function calcTotalValue(address creditAccount)
        external
        view
        returns (uint256 total, uint256 twv);
```
&&
````
function calcCreditAccountHealthFactor(address creditAccount)
        external
        view
        returns (uint256 hf);
```

**Comment by steve0xp** [comment]
Closing this as we figure this out in issue #14
